### ISSUE TITLE
consommateurs

### ISSUE THREAD

**Issue by agnez** [pcolmant/repanier#16]
Salut Patrick,
Voici mon premier ticket :) 
Je fais les premiers pas sur une instance toute fraîche installé par Kenny. 
Il m'a crée un utilisateur. Je commence à créer quelques consommateurs, mais mon propre compte n'apparaît pas dans la liste de consommateurs. Quand je veux m'ajouter, en créant un nouveau utilisateur avec mon nom, je reçois l'erreur que l'utilisateur existe déjà. Logique, puisque je suis connecté avec. Mais comment m'ajouter aux consommateurs ?
Merci !
Agnez

**Comment by pcolmant** [comment]
Bonjour Agnez,

[Tu trouveras la cause et la réponse ici](https://ps.repanier.be/t/creer-un-utilisateur-de-base/86/3).
