### ISSUE TITLE
migration à une version récente de openpyxl

### ISSUE THREAD

**Issue by ghost** [pcolmant/repanier#4]
> Pour info, comme django-import-export embarque tablib qui embarque un
> openpyxl v2.X, j'ai créé repanier.xlsx.extended_formats.py pour mapper vers
> l'openpyxl v1.X utilisé par repanier lors des importations de fichiers xlsx
> avec django-import-export.

**Comment by pcolmant** [comment]
Python doesn't help to solve librairies dependencies. Virtualenv helps, but only to solve "one" librairie dependency per virtualenv. Not multiple versions of a librairy.

**Comment by pcolmant** [comment]
Please propose a pull request.
