### ISSUE TITLE
Repanier should be silent on production

### ISSUE THREAD

**Issue by ghost** [pcolmant/repanier#6]
Running on production Repanier should be silent when there is no error.

**Comment by ghost** [comment]
Ceci n'est pas du tout urgent pour moi, j'ai ouvert ce ticket pour lancer la discussion. On pourrait utiliser le module logging pour séparer les messages informatifs des erreurs, etc
 https://docs.djangoproject.com/en/1.11/topics/logging/#using-logging
 https://www.python.org/dev/peps/pep-0333/#error-handling

**Comment by pcolmant** [comment]
Merci pour ce feed back. Le module logging est depuis utilisé.
